require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserSessonsController do

  # This should return the minimal set of attributes required to create a valid
  # UserSesson. As you add validations to UserSesson, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all user_sessons as @user_sessons" do
      user_sesson = UserSesson.create! valid_attributes
      get :index
      assigns(:user_sessons).should eq([user_sesson])
    end
  end

  describe "GET show" do
    it "assigns the requested user_sesson as @user_sesson" do
      user_sesson = UserSesson.create! valid_attributes
      get :show, :id => user_sesson.id.to_s
      assigns(:user_sesson).should eq(user_sesson)
    end
  end

  describe "GET new" do
    it "assigns a new user_sesson as @user_sesson" do
      get :new
      assigns(:user_sesson).should be_a_new(UserSesson)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_sesson as @user_sesson" do
      user_sesson = UserSesson.create! valid_attributes
      get :edit, :id => user_sesson.id.to_s
      assigns(:user_sesson).should eq(user_sesson)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserSesson" do
        expect {
          post :create, :user_sesson => valid_attributes
        }.to change(UserSesson, :count).by(1)
      end

      it "assigns a newly created user_sesson as @user_sesson" do
        post :create, :user_sesson => valid_attributes
        assigns(:user_sesson).should be_a(UserSesson)
        assigns(:user_sesson).should be_persisted
      end

      it "redirects to the created user_sesson" do
        post :create, :user_sesson => valid_attributes
        response.should redirect_to(UserSesson.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_sesson as @user_sesson" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserSesson.any_instance.stub(:save).and_return(false)
        post :create, :user_sesson => {}
        assigns(:user_sesson).should be_a_new(UserSesson)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserSesson.any_instance.stub(:save).and_return(false)
        post :create, :user_sesson => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_sesson" do
        user_sesson = UserSesson.create! valid_attributes
        # Assuming there are no other user_sessons in the database, this
        # specifies that the UserSesson created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UserSesson.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => user_sesson.id, :user_sesson => {'these' => 'params'}
      end

      it "assigns the requested user_sesson as @user_sesson" do
        user_sesson = UserSesson.create! valid_attributes
        put :update, :id => user_sesson.id, :user_sesson => valid_attributes
        assigns(:user_sesson).should eq(user_sesson)
      end

      it "redirects to the user_sesson" do
        user_sesson = UserSesson.create! valid_attributes
        put :update, :id => user_sesson.id, :user_sesson => valid_attributes
        response.should redirect_to(user_sesson)
      end
    end

    describe "with invalid params" do
      it "assigns the user_sesson as @user_sesson" do
        user_sesson = UserSesson.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserSesson.any_instance.stub(:save).and_return(false)
        put :update, :id => user_sesson.id.to_s, :user_sesson => {}
        assigns(:user_sesson).should eq(user_sesson)
      end

      it "re-renders the 'edit' template" do
        user_sesson = UserSesson.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserSesson.any_instance.stub(:save).and_return(false)
        put :update, :id => user_sesson.id.to_s, :user_sesson => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_sesson" do
      user_sesson = UserSesson.create! valid_attributes
      expect {
        delete :destroy, :id => user_sesson.id.to_s
      }.to change(UserSesson, :count).by(-1)
    end

    it "redirects to the user_sessons list" do
      user_sesson = UserSesson.create! valid_attributes
      delete :destroy, :id => user_sesson.id.to_s
      response.should redirect_to(user_sessons_url)
    end
  end

end
